apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
    role: server
spec:
  type: ClusterIP
  ports:
    - port: 8989
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sonarr
    role: server
