---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: digitalocean-dns
  namespace: cert-manager
  creationTimestamp:
spec:
  template:
    metadata:
      name: digitalocean-dns
      namespace: cert-manager
      creationTimestamp:
    type: Generic
  encryptedData:
    access-token: AgCqAJ57UUfVwCrWymtIn2owysH4ZLM2OrKhIDsB6v2LcD8UD5wFSchkasv5EsvpqduGeYQh5vjWMKWgwL1JxZAS4OLXWsQqwKG9Q8p7stDZnN63SZG+r1xzr3O3P/bD4WlIMZeLuimU2TFQ1VtYubtmQjeef45qFCfcX1CyV6X0p+4TntpVQE1YY5hC3sjphKMZLvxiX9G/nBWbzAiuIVe3ZHJlAfOZvVzrrWz4MMSn3rY5VbLtLbbcYdsP/nkeBAE9N+zHChJ+B2ZfV8qotZurdFnXB48/AQPVNwALH52N4GGsjpNSWtYPPKBPuG/5CVTN7ELhaq+gy2B3n3S0LUuC1+n9t/Xjas7eXe2EqqnrcxI2Hv2xxR9FEOyEF3dt9dxTxakZrrtRp6QyCDO9bpx4hfWrzmR/ZINdqXNGbrLEdayMahPPCufXbr2/txvyzBDvhCNU40UruzI3h+OqTb2VKLMpnjzet8MNx0zYFQ3b3UQyzzaMv9R01gvP/pzByi9hY0ZJQVjqEmpiaMROL2DN9GEJFy8Qb+Gl2VJ5+arRC23wqOBfDMOW3/R0H5UMAMt5QV0ZZtxdIaWuN0PFR9PBJ/VrnNlTOz+cl8KRsDzw9eBeuMf0yiYIAiomJFsBKlnfc96d7MmTLdR1JGkFDd59tP4Nb0UTs3Tkf7lBd96EYLVvOv08CT/sm9S/2FT2YxIx9+l/8ZgCTSaflS85YQqDnlQ6W0LDCLP5gL5qS8Uf9Z5esxC42v5V1Eo/zt67FTwl6TIAOPbfZQwCGbBsFCFZ
status: {}
