apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: backend
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] > 0.90
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:9090
        query: >+
          sum(
            rate(traefik_backend_requests_total{backend="{{args.backend}}",code!~"[4-5].*"}[20s]))
            /
            sum(rate(traefik_backend_requests_total{backend="{{args.backend}}"}[20s])
          )
