kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-config
  labels:
    app: qbittorrent
    role: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
