kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-cache
  labels:
    app: jellyfin
    role: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-config
  labels:
    app: jellyfin
    role: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
