apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argo
spec:
  description: Kitsune Kubernetes boilerplate bits

  sourceRepos:
  - '*'

  destinations:
  - namespace: kube-system
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: 'policy'
    kind: PodSecurityPolicy
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition

  orphanedResources:
    warn: true
