kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: immich
    role: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: immich
    role: db
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: immich
      role: db
  template:
    metadata:
      labels:
        app: immich
        role: db
    spec:
      tolerations:
        - key: valerauko.net/local
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: immich
            - secretRef:
                name: immich
          env:
            - name: POSTGRES_INITDB_ARGS
              value: '--data-checksums'
          volumeMounts:
            - name: database
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: immich
    role: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      name: postgres
      targetPort: postgres
  selector:
    app: immich
    role: db
