kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: immich
    role: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-v18
  labels:
    app: immich
    role: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: immich
    role: db
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: immich
      role: db
  template:
    metadata:
      labels:
        app: immich
        role: db
    spec:
      tolerations:
        - key: valerauko.net/local
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:18-vectorchord1.1.1-pgvector0.8.5@sha256:e1c25329747ba6fec8b0cc0817be95713916a78be6654ba544165c0897aadf2c
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: immich
            - secretRef:
                name: immich
          env:
            - name: POSTGRES_INITDB_ARGS
              value: '--data-checksums'
          volumeMounts:
            - name: database
              mountPath: /var/lib/postgresql/18/docker
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: postgres-v18

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: immich
    role: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      name: postgres
      targetPort: postgres
  selector:
    app: immich
    role: db
