apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: home-assistant
  nodeSelector:
    kubernetes.io/hostname: homelab
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: front-proxy
          image: nginx:1.29.1
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config-volume
              subPath: nginx.conf
      tolerations:
        - key: valerauko.net/local
          effect: NoSchedule
          operator: Exists
      volumes:
        - name: nginx-config-volume
          configMap:
            name: home-assistant
