apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  labels:
    app: home-assistant
  annotations:
    kubernetes.io/ingress.class: tailscale
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
      - home.dekiru.tech
      secretName: dekiru-tech-tls
  defaultBackend:
    service:
      name: home-assistant
      port:
        name: http
