apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo
spec:
  project: system

  source:
    repoURL: https://github.com/helm/charts.git
    targetRevision: HEAD
    path: stable/sealed-secrets

    helm:
      releaseName: sealed-secrets

      valueFiles:
      - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
