apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "05"
spec:
  description: System stuff

  sourceRepos:
  - '*'

  destinations:
  - namespace: argo-cd
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: dns-hole
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: tailscale
    server: https://kubernetes.default.svc
  - namespace: pihole
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: 'policy'
    kind: PodSecurityPolicy
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'cert-manager.io'
    kind: ClusterIssuer
  - group: 'storage.k8s.io'
    kind: StorageClass
  - group: 'storage.k8s.io'
    kind: CSIDriver
  - group: 'networking.k8s.io'
    kind: IngressClass
  - group: 'apiregistration.k8s.io'
    kind: APIService
  - group: 'admissionregistration.k8s.io'
    kind: ValidatingWebhookConfiguration
  - group: 'admissionregistration.k8s.io'
    kind: MutatingWebhookConfiguration
  - group: 'tailscale.com'
    kind: ProxyGroup
