apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: system
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "1.*"

    helm:
      releaseName: cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      selfHeal: true
