apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: system
  source:
    repoURL: https://github.com/helm/charts.git
    targetRevision: master
    path: stable/traefik

    helm:
      releaseName: traefik

      values: |
        kubernetes:
          ingressEndpoint:
            publishedService: "kube-system/traefik"
        ssl:
          enabled: true
          enforced: true
        acme:
          enabled: true
          email: valerauko@gmail.com
          staging: false
          logging: true
          domains:
            enabled: true
            domainsList:
              - main: "*.valerauko.net"
              - sans:
                  - "valerauko.net"
              - main: "*.dekiru.tech"
              - sans:
                  - "dekiru.tech"
              - main: "*.erdos.tech"
              - sans:
                  - "erdos.tech"
              - main: "notredrevie.ws"
          challengeType: dns-01
          dnsProvider:
            name: linodev4
            linodev4: { LINODE_TOKEN: '' } # chart bug fix hack
            existingSecretName: host-api-token
        accessLogs:
          enabled: true
        dashboard:
          enabled: false
        rbac:
          enabled: true
        metrics:
          prometheus:
            enabled: true
        deployment:
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "9100"

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
