apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: system
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "9.*"

    helm:
      releaseName: traefik

      values: |
        globalArguments:
          - "--global.checknewversion"
        providers:
          kubernetesCRD:
            enabled: true
            namespaces:
              - default
          kubernetesIngress:
            publishedService:
              enabled: true
        logs:
          general:
            level: INFO
          access:
            enabled: true
        rbac:
          enabled: true
        deployment:
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "9100"
        ports:
          web:
            redirectTo: websecure
          websecure:
            tls:
              enabled: true
              certResolver: letsencrypt
              domains:
                - main: "*.valerauko.net"
                - sans:
                    - "valerauko.net"
                - main: "*.dekiru.tech"
                - sans:
                    - "dekiru.tech"
                - main: "*.erdos.tech"
                - sans:
                    - "erdos.tech"
                - main: "notredrevie.ws"
        additionalArguments:
          - "--certificatesresolvers.letsencrypt.acme.email=valerauko@gmail.com"
          - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
          - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=linode"
        persistence:
          enabled: true
          size: 32Mi
        envFrom:
          - secretRef:
              name: host-api-token

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
