apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linode-dns-hook
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: system
  source:
    repoURL: https://github.com/linode/cert-manager-webhook-linode.git
    targetRevision: master
    path: deploy/cert-manager-webhook-linode

    helm:
      releaseName: cert-manager-webhook-linode
      values: |
        api:
          groupName: valerauko.net
        image:
          repository: linode/cert-manager-webhook-linode
          tag: v0.3.0
        deployment:
          secretName: linode
          logLevel: false

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      selfHeal: true
