apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linode
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: system
  source:
    repoURL: https://github.com/linode/linode-blockstorage-csi-driver.git
    targetRevision: v0.8.4
    path: helm-chart/csi-driver

    helm:
      releaseName: linode-csi

      values: |
        defaultStorageClass: local-path
        secretRef:
          name: linode
          apiTokenRef: token
          regionRef: region

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
