apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linode-csi
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  project: system
  source:
    repoURL: https://github.com/linode/linode-blockstorage-csi-driver.git
    targetRevision: v0.8.5
    path: helm-chart/csi-driver

    helm:
      releaseName: linode-csi

      values: |
        defaultStorageClass: local-path
        secretRef:
          name: linode
          apiTokenRef: token
          regionRef: region
        csiNodeDriverRegistrar:
          env:
            - name: LINODE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: linode
                  key: token
        controller:
          nodeSelector:
            topology.linode.com/region: ap-northeast

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
