apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  project: system
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale/tailscale-operator
    targetRevision: "*"

    helm:
      releaseName: tailscale

  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale

  syncPolicy:
    automated:
      selfHeal: true
