apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-hole
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "18"
spec:
  project: system
  source:
    repoURL: https://github.com/valerauko/sut.git
    targetRevision: master
    path: homelab/dns-hole

  destination:
    server: https://kubernetes.default.svc
    namespace: dns-hole

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
