apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: system
  source:
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: master
    path: charts/argo-cd

    helm:
      releaseName: argo-cd
      values: |
        controller:
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8082"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
          livenessProbe:
            timeoutSeconds: "30"
          readinessProbe:
            timeoutSeconds: "30"
        server:
          extraArgs:
          - "--insecure"
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8083"
          livenessProbe:
            timeoutSeconds: "30"
          readinessProbe:
            timeoutSeconds: "30"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
              ingress.kubernetes.io/protocol: http
            hosts:
            - argo.dekiru.tech
            tls:
            - hosts:
              - argo.dekiru.tech
          config:
            url: https://argo.dekiru.tech
        repoServer:
          extraArgs:
            - "--parallelismlimit=1"
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8084"


  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

  syncPolicy:
    automated:
      selfHeal: true
