apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: system
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "3.*"

    helm:
      releaseName: argo-cd
      values: |
        controller:
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8082"
          livenessProbe:
            timeoutSeconds: "30"
          readinessProbe:
            timeoutSeconds: "30"
        server:
          extraArgs:
          - "--insecure"
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8083"
          livenessProbe:
            timeoutSeconds: "30"
          readinessProbe:
            timeoutSeconds: "30"
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
              ingress.kubernetes.io/protocol: http
            hosts:
            - argo.dekiru.tech
            tls:
            - hosts:
              - argo.dekiru.tech
        repoServer:
          extraArgs:
            - "--parallelismlimit=1"
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8084"

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

  syncPolicy:
    automated:
      selfHeal: true
