apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-notifications
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: system
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-notifications
    targetRevision: "1.*"

    helm:
      releaseName: argo-notifications
      values: |
        argocdUrl: https://argo.dekiru.tech
        secret:
          create: false
        notifiers:
          service.grafana: |
            apiKey: $grafana-token
            apiUrl: http://grafana.monitoring.svc.cluster.local/api
        triggers:
          trigger.on-deployed: |
            - description: Application is synced and healthy. Triggered once per commit.
              oncePer: app.status.sync.revision
              when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
          trigger.on-health-degraded: |
            - description: Application has degraded
              when: app.status.health.status == 'Degraded'
          trigger.on-sync-failed: |
            - description: Application syncing has failed
              when: app.status.operationState.phase in ['Error', 'Failed']
          trigger.on-sync-status-unknown: |
            - description: Application status is 'Unknown'
              when: app.status.sync.status == 'Unknown'
        subscriptions:
          - recipients:
              - grafana:success
            triggers:
              - on-deployed
          - recipients:
              - grafana:failed
            triggers:
              - on-sync-failed
          - recipients:
              - grafana:problem
            triggers:
              - on-sync-status-unknown
              - on-health-degraded

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

  syncPolicy:
    automated:
      selfHeal: true
