apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "*"
    chart: prometheus

    helm:
      releaseName: prometheus

      values: |
        server:
          retention: "168h"
          statefulSet:
            enabled: true
          persistentVolume:
            storageClass: longhorn
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - argocd-application-controller
                  topologyKey: kubernetes.io/hostname
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - mariadb
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - primary
                  topologyKey: kubernetes.io/hostname
        alertmanager:
          enabled: false
        networkPolicy:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      selfHeal: true
