apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "*"
    chart: prometheus

    helm:
      releaseName: prometheus

      values: |
        server:
          global:
            scrape_interval: 10s
          statefulSet:
            enabled: true
          persistentVolume:
            storageClass: longhorn
        alertmanager:
          statefulSet:
            enabled: true
          persistentVolume:
            storageClass: longhorn
        networkPolicy:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      selfHeal: true
