apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "8.14.0"
    chart: grafana

    helm:
      releaseName: grafana

      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: traefik
          hosts:
            - grafana.dekiru.tech
          tls:
            - hosts:
                - grafana.dekiru.tech
              secretName: dekiru-tech-tls
        persistence:
          enabled: true
          type: statefulset
        plugins:
          - grafana-piechart-panel

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      selfHeal: true
