apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "32"
spec:
  project: monitoring
  source:
    repoURL: https://github.com/grafana/loki
    targetRevision: master
    path: production/helm/loki/loki-stack

    helm:
      releaseName: loki

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      selfHeal: true
