apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: books
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: default
  source:
    repoURL: https://github.com/valerauko/books.git
    targetRevision: master
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
