apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: sites
  source:
    repoURL: registry-1.docker.io
    targetRevision: "9.8.1"
    chart: bitnamicharts/mariadb

    helm:
      releaseName: mariadb

      values: |
        rbac:
          create: true
        auth:
          existingSecret: mariadb
          database: valenet
          username: valerauko
          forcePassword: true
        architecture: standalone
        primary:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - argocd-application-controller
                  topologyKey: kubernetes.io/hostname
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - prometheus
                      - key: component
                        operator: In
                        values:
                          - server
                  topologyKey: kubernetes.io/hostname
          persistence:
            storageClass: "linode-block-storage-retain"
            size: "15Gi"
        metrics:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
