apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: sites
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: bitnami/mariadb

    helm:
      releaseName: mariadb

      values: |
        rbac:
          create: true
        existingSecret: mariadb
        root:
          forcePassword: true
          injectSecretsAsVolume: true
        db:
          name: valenet
          user: valerauko
          forcePassword: true
          injectSecretsAsVolume: true
        replication:
          persistence:
            enabled: false
          forcePassword: true
          injectSecretsAsVolume: true
        metrics:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
