apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: sites
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "9.*"
    chart: mariadb

    helm:
      releaseName: mariadb

      values: |
        rbac:
          create: true
        auth:
          existingSecret: mariadb
          database: valenet
          username: valerauko
          forcePassword: true
        architecture: standalone
        primary:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/master
                        operator: DoesNotExist
          persistence:
            storageClass: "linode-block-storage-retain"
            size: "15Gi"
        metrics:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
