apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notred
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "61"
spec:
  project: sites
  source:
    repoURL: https://github.com/valerauko/pehelypress.git
    targetRevision: master
    path: "."

    helm:
      releaseName: notred

      values: |
        database:
          existingSecret: "notred-mariadb-creds"
        debug: false
        php:
          file_uploads: "On"
          upload_max_filesize: "20M"
          post_max_size: "20M"
          memory_limit: "64M"
          max_execution_time: "60"
        ingress:
          enabled: true
          annotations:
            "kubernetes.io/ingress.class": traefik
          hosts:
            - host: notredrevie.ws
              paths:
                - "/"
          tls:
            - hosts:
                - notredrevie.ws
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
            effect: NoSchedule


  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
