apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: climbing-static
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "62"
spec:
  project: sites
  source:
    repoURL: https://github.com/valerauko/climbing.git
    targetRevision: master
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
