apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocket-chat
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  project: sites
  source:
    repoURL: https://github.com/helm/charts.git
    targetRevision: master
    path: stable/rocketchat

    helm:
      releaseName: rocket-chat
      values: |
        host: rocket.dekiru.tech
        ingress:
          enabled: true
          annotations:
            "kubernetes.io/ingress.class": traefik
          tls:
            - hosts:
                - rocket.dekiru.tech


  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
