apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile-traefik
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "72"
spec:
  project: sites
  source:
    repoURL: https://github.com/valerauko/sut.git
    targetRevision: master
    path: seafile-traefik

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
