apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yureta
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "80"
spec:
  project: projects
  source:
    repoURL: https://github.com/valerauko/dekiru.git
    targetRevision: master
    path: quake/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: projects

  syncPolicy:
    automated:
      selfHeal: true
