apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advent
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "84"
spec:
  project: sites
  source:
    repoURL: https://github.com/valerauko/personal-advent.git
    targetRevision: v1.1.0
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
