apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "93"
spec:
  project: sites
  source:
    repoURL: https://github.com/valerauko/sut.git
    targetRevision: master
    path: homelab/jellyfin

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

  syncPolicy:
    automated:
      selfHeal: true
