apiVersion: v1
kind: Service
metadata:
  name: whoami-test
  labels:
    app: whoami-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: whoami-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-test
  labels:
    app: whoami-test
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: whoami-test
  template:
    metadata:
      labels:
        app: whoami-test
    spec:
      containers:
        - name: whoami-test
          image: containous/whoami:latest
          ports:
            - name: http
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-test
  labels:
    app: whoami-test
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
      - whoami.dekiru.tech
  rules:
    - host: whoami.dekiru.tech
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: whoami-test
                port:
                  name: http
