apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx-test

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test
  labels:
    app: nginx-test
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
      - nginx-test.dekiru.tech
  rules:
    - host: nginx-test.dekiru.tech
      http:
        paths:
          - backend:
              service:
                name: nginx-test
                port:
                  name: http
            path: /
            pathType: Prefix

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx-test
  nodeSelector:
    kubernetes.io/hostname: homelab
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-test
          image: nginx:1.29.1
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
