apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr
    role: server
spec:
  type: ClusterIP
  ports:
    - port: 9696
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: prowlarr
    role: server
