apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo
spec:
  project: system

  source:
    repoURL: https://github.com/valerauko/sut
    targetRevision: 49888e6f125427bf1a5c6f5b691a32d2cd2a8813
    path: system/argo

    helm:
      releaseName: argo-cd

  destination:
    server: https://kubernetes.default.svc
    namespace: argo

  syncPolicy:
    automated:
      selfHeal: true
