apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo
spec:
  project: monitoring

  source:
    repoURL: https://github.com/valerauko/sut.git
    targetRevision: HEAD
    path: system/grafana

    helm:
      releaseName: grafana

      valueFiles:
      - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      selfHeal: true
