apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: monitoring.kitsune.social
  dnsNames:
  - monitoring.kitsune.social
  acme:
    config:
    - dns01:
        provider: digitalocean
      domains:
      - monitoring.kitsune.social
